Main.o: Main.cpp NeuralNetwork.cpp Genome.cpp Parameters.cpp Substrate.cpp Population.cpp Random.cpp Innovation.cpp Species.cpp
	g++ -g Main.cpp NeuralNetwork.cpp Genome.cpp Parameters.cpp Substrate.cpp Population.cpp Random.cpp Innovation.cpp Species.cpp -std=c++11  -lboost_system -lX11 -L/usr/lib64 -lstdc++ -lm
